// <auto-generated />
using System;
using CustomFumenProviderWebServer.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomFumenProviderWebServer.Migrations
{
    [DbContext(typeof(FumenDataDB))]
    [Migration("20241016032842_AddMoreProperties")]
    partial class AddMoreProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CustomFumenProviderWebServer.Models.Tables.FumenDifficult", b =>
                {
                    b.Property<int>("MusicId")
                        .HasColumnType("int");

                    b.Property<int>("DifficultIndex")
                        .HasColumnType("int");

                    b.Property<float>("Bpm")
                        .HasColumnType("float");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<float>("Level")
                        .HasColumnType("float");

                    b.HasKey("MusicId", "DifficultIndex");

                    b.ToTable("FumenDifficults");
                });

            modelBuilder.Entity("CustomFumenProviderWebServer.Models.Tables.FumenSet", b =>
                {
                    b.Property<int>("MusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MusicId"));

                    b.Property<string>("Artist")
                        .HasColumnType("longtext");

                    b.Property<int>("BossCardId")
                        .HasColumnType("int");

                    b.Property<string>("BossCardName")
                        .HasColumnType("longtext");

                    b.Property<int>("BossLevel")
                        .HasColumnType("int");

                    b.Property<int>("BossLockHpCoef")
                        .HasColumnType("int");

                    b.Property<int>("BossVoiceNo")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .HasColumnType("longtext");

                    b.Property<int>("MusicRightsId")
                        .HasColumnType("int");

                    b.Property<string>("MusicRightsName")
                        .HasColumnType("longtext");

                    b.Property<int>("PublishState")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.Property<string>("VersionName")
                        .HasColumnType("longtext");

                    b.Property<string>("WaveAttribute")
                        .HasColumnType("longtext");

                    b.HasKey("MusicId");

                    b.ToTable("FumenSets");
                });

            modelBuilder.Entity("CustomFumenProviderWebServer.Models.Tables.FumenDifficult", b =>
                {
                    b.HasOne("CustomFumenProviderWebServer.Models.Tables.FumenSet", "FumenSet")
                        .WithMany("FumenDifficults")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FumenSet");
                });

            modelBuilder.Entity("CustomFumenProviderWebServer.Models.Tables.FumenSet", b =>
                {
                    b.Navigation("FumenDifficults");
                });
#pragma warning restore 612, 618
        }
    }
}
